### ISSUE TITLE
1.2.1 Tensorの生成と変換に誤植？

### ISSUE THREAD

**Issue by Justmeaning** [lucidfrontier45/PyTorch-Book#1]
Pytorchの初心者です。

#入れ子のlistを渡して作成
t = torch.Tensor([[1,2],[3,4]])

#GPUにTensorを作成
t = torch.Tensor([[1,2],[3,4]])

と書いてあり両方とも同じなのですが、前者は誤植ですか？
どうするとCPUのTensor、GPUのTensorそれぞれになるのかが分かりませんでした。

**Comment by lucidfrontier45** [comment]
ご連絡ありがとうございます。

ふたつ目のコードは
```py
t = torch.cuda.FloatTensor([[1,2],[3,4]])
```
の間違いです。ご指摘ありがとうございます。
後ほどKindle版も修正いたします。

**Comment by lucidfrontier45** [comment]
```py
# GPU上のTensorはcpuメソッドで
# 一度CPUのTensorに変換する必要がある
t = torch.Tensor([[1, 2], [3, 4]])
x = t.cpu().numpy()
```

ここも

```py
t = torch.cuda.FloatTensor([[1,2],[3,4]])
```

の間違いですね。

**Comment by lucidfrontier45** [comment]
Kindle版も修正が適用されたと思いますので更新をダウンロードしてください。
