### ISSUE TITLE
誤植：2.1 確率モデルと最尤推定

### ISSUE THREAD

**Issue by Justmeaning** [lucidfrontier45/PyTorch-Book#2]
1.　1行目：xが１つ多い？
「確率モデルとは次のように変数xxが」

2.　対数尤度の説明の後に１〜２つの誤植
「例えば正規分布の期待値パラメータμ\muの最尤推定は次のように対数尤度をμいて偏微分し」

**Comment by lucidfrontier45** [comment]
確認しました。次の修正版で反映します。
